services:
  atm-system:
    build: .
    container_name: atm-system
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - API_VERSION=1.0.0
      - CORS_ORIGIN=*
      - LOG_LEVEL=info
      - HEALTH_CHECK_PATH=/health
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - atm-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: atm-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - atm-system
    networks:
      - atm-network
    profiles:
      - production
    restart: unless-stopped

networks:
  atm-network:
    driver: bridge